version: '3.8'

services:
  web:
    build: .
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app